// Cross-runtime grammar tables: one authored pattern, two runtimes, zero
// drift. The contract: the SOURCE grammars were battle-tested under
// Python's Unicode semantics, so both loaders expand \s \S \w \W \b \B
// at compile time to explicit constructs frozen from those semantics
// (measured, not assumed: JS \s is Unicode-ish in every mode, JS \w/\b
// are always ASCII, Python re.ASCII strips both — three-way divergence
// on NBSP-bearing and accented text, 62 + 242 real findings before the
// expansions). \d stays ASCII deliberately: digits in legal text are
// ASCII and the unicode-trap scanner flags exotic digits. Python
// compiles with re.ASCII; JS never uses the u flag. The validator bans
// the constructs whose semantics genuinely diverge; everything else is
// ordinary regex. Named groups are authored JS-style ((?<name>…)); the
// Python loader translates to (?P<name>…). Lookbehind is allowed
// because Python only compiles the fixed-width form and the mandatory
// dual-runtime vector check therefore rejects any table Python cannot
// hold — the gate is structural, not syntactic. A table may carry
// `defs`, named pattern fragments spliced in via {{name}} before
// validation and compilation, mirroring how the source grammars
// compose rf-strings.

export interface GrammarVector {
  input: string;
  /** Expected named-group captures of the FIRST match; null = must not match. */
  groups: Record<string, string> | null;
  /** Optional expected canonicalized values (subset of groups). */
  canonical?: Record<string, string>;
}

export interface GrammarCanonical {
  lowercase?: string[];
  map?: Record<string, Record<string, string>>;
  strip?: Record<string, string>;
}

export interface GrammarEntry {
  id: string;
  pattern: string;
  /** Subset of "ims". */
  flags: string;
  canonical: GrammarCanonical;
  vectors: GrammarVector[];
}

export interface GrammarTable {
  format: string;
  description?: string;
  /** Named pattern fragments, spliced into patterns via {{name}}. */
  defs?: Record<string, string>;
  entries: GrammarEntry[];
}

export const GRAMMAR_TABLE_FORMAT = "beaver-grammar-table:v1";

/**
 * Splice {{name}} references to table defs into a pattern. Runs to a
 * fixpoint so defs may reference other defs; throws on an unknown name
 * or a reference cycle. Must stay byte-equivalent with the Python
 * loader's expansion.
 */
export function expandGrammarPattern(
  source: string,
  defs: Record<string, string> = {},
): string {
  let out = source;
  for (let pass = 0; ; pass += 1) {
    const next = out.replace(/\{\{([A-Za-z_][A-Za-z0-9_]*)\}\}/g, (_, name) => {
      const value = defs[name];
      if (value === undefined) {
        throw new Error(`grammar def {{${name}}} is not defined`);
      }
      return value;
    });
    if (next === out) return out;
    if (pass >= 10) {
      throw new Error("grammar defs reference each other in a cycle");
    }
    out = next;
  }
}

/**
 * The whitespace set Python's Unicode \s matched when the source
 * grammars were battle-tested: ASCII whitespace + the C1/Unicode spaces
 * (NBSP, ogham, en/em spaces, line/para separators, narrow no-break,
 * math space, ideographic) + the \x1c-\x1f separators and \x85. NOT
 * ﻿ (JS-only). Both loaders expand \s/\S to this class so both
 * runtimes reproduce the source behavior exactly.
 */
const SOURCE_WHITESPACE =
  " \\t\\n\\r\\f\\v\\x1c-\\x1f\\x85\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000";

/**
 * The BMP word class Python's Unicode \w matched when the source
 * grammars were battle-tested. Generated by the engine's
 * tools/gen_word_class.py (python 3.11.15, unicodedata 14.0.0) and
 * FROZEN — regenerating changes match behavior and needs the full
 * differential + FR gates. Do not hand-edit.
 */
const SOURCE_WORD = "0-9A-Z_a-z\\u00aa\\u00b2\\u00b3\\u00b5\\u00b9\\u00ba\\u00bc-\\u00be\\u00c0-\\u00d6\\u00d8-\\u00f6\\u00f8-\\u02c1\\u02c6-\\u02d1\\u02e0-\\u02e4\\u02ec\\u02ee\\u0370-\\u0374\\u0376\\u0377\\u037a-\\u037d\\u037f\\u0386\\u0388-\\u038a\\u038c\\u038e-\\u03a1\\u03a3-\\u03f5\\u03f7-\\u0481\\u048a-\\u052f\\u0531-\\u0556\\u0559\\u0560-\\u0588\\u05d0-\\u05ea\\u05ef-\\u05f2\\u0620-\\u064a\\u0660-\\u0669\\u066e\\u066f\\u0671-\\u06d3\\u06d5\\u06e5\\u06e6\\u06ee-\\u06fc\\u06ff\\u0710\\u0712-\\u072f\\u074d-\\u07a5\\u07b1\\u07c0-\\u07ea\\u07f4\\u07f5\\u07fa\\u0800-\\u0815\\u081a\\u0824\\u0828\\u0840-\\u0858\\u0860-\\u086a\\u0870-\\u0887\\u0889-\\u088e\\u08a0-\\u08c9\\u0904-\\u0939\\u093d\\u0950\\u0958-\\u0961\\u0966-\\u096f\\u0971-\\u0980\\u0985-\\u098c\\u098f\\u0990\\u0993-\\u09a8\\u09aa-\\u09b0\\u09b2\\u09b6-\\u09b9\\u09bd\\u09ce\\u09dc\\u09dd\\u09df-\\u09e1\\u09e6-\\u09f1\\u09f4-\\u09f9\\u09fc\\u0a05-\\u0a0a\\u0a0f\\u0a10\\u0a13-\\u0a28\\u0a2a-\\u0a30\\u0a32\\u0a33\\u0a35\\u0a36\\u0a38\\u0a39\\u0a59-\\u0a5c\\u0a5e\\u0a66-\\u0a6f\\u0a72-\\u0a74\\u0a85-\\u0a8d\\u0a8f-\\u0a91\\u0a93-\\u0aa8\\u0aaa-\\u0ab0\\u0ab2\\u0ab3\\u0ab5-\\u0ab9\\u0abd\\u0ad0\\u0ae0\\u0ae1\\u0ae6-\\u0aef\\u0af9\\u0b05-\\u0b0c\\u0b0f\\u0b10\\u0b13-\\u0b28\\u0b2a-\\u0b30\\u0b32\\u0b33\\u0b35-\\u0b39\\u0b3d\\u0b5c\\u0b5d\\u0b5f-\\u0b61\\u0b66-\\u0b6f\\u0b71-\\u0b77\\u0b83\\u0b85-\\u0b8a\\u0b8e-\\u0b90\\u0b92-\\u0b95\\u0b99\\u0b9a\\u0b9c\\u0b9e\\u0b9f\\u0ba3\\u0ba4\\u0ba8-\\u0baa\\u0bae-\\u0bb9\\u0bd0\\u0be6-\\u0bf2\\u0c05-\\u0c0c\\u0c0e-\\u0c10\\u0c12-\\u0c28\\u0c2a-\\u0c39\\u0c3d\\u0c58-\\u0c5a\\u0c5d\\u0c60\\u0c61\\u0c66-\\u0c6f\\u0c78-\\u0c7e\\u0c80\\u0c85-\\u0c8c\\u0c8e-\\u0c90\\u0c92-\\u0ca8\\u0caa-\\u0cb3\\u0cb5-\\u0cb9\\u0cbd\\u0cdd\\u0cde\\u0ce0\\u0ce1\\u0ce6-\\u0cef\\u0cf1\\u0cf2\\u0d04-\\u0d0c\\u0d0e-\\u0d10\\u0d12-\\u0d3a\\u0d3d\\u0d4e\\u0d54-\\u0d56\\u0d58-\\u0d61\\u0d66-\\u0d78\\u0d7a-\\u0d7f\\u0d85-\\u0d96\\u0d9a-\\u0db1\\u0db3-\\u0dbb\\u0dbd\\u0dc0-\\u0dc6\\u0de6-\\u0def\\u0e01-\\u0e30\\u0e32\\u0e33\\u0e40-\\u0e46\\u0e50-\\u0e59\\u0e81\\u0e82\\u0e84\\u0e86-\\u0e8a\\u0e8c-\\u0ea3\\u0ea5\\u0ea7-\\u0eb0\\u0eb2\\u0eb3\\u0ebd\\u0ec0-\\u0ec4\\u0ec6\\u0ed0-\\u0ed9\\u0edc-\\u0edf\\u0f00\\u0f20-\\u0f33\\u0f40-\\u0f47\\u0f49-\\u0f6c\\u0f88-\\u0f8c\\u1000-\\u102a\\u103f-\\u1049\\u1050-\\u1055\\u105a-\\u105d\\u1061\\u1065\\u1066\\u106e-\\u1070\\u1075-\\u1081\\u108e\\u1090-\\u1099\\u10a0-\\u10c5\\u10c7\\u10cd\\u10d0-\\u10fa\\u10fc-\\u1248\\u124a-\\u124d\\u1250-\\u1256\\u1258\\u125a-\\u125d\\u1260-\\u1288\\u128a-\\u128d\\u1290-\\u12b0\\u12b2-\\u12b5\\u12b8-\\u12be\\u12c0\\u12c2-\\u12c5\\u12c8-\\u12d6\\u12d8-\\u1310\\u1312-\\u1315\\u1318-\\u135a\\u1369-\\u137c\\u1380-\\u138f\\u13a0-\\u13f5\\u13f8-\\u13fd\\u1401-\\u166c\\u166f-\\u167f\\u1681-\\u169a\\u16a0-\\u16ea\\u16ee-\\u16f8\\u1700-\\u1711\\u171f-\\u1731\\u1740-\\u1751\\u1760-\\u176c\\u176e-\\u1770\\u1780-\\u17b3\\u17d7\\u17dc\\u17e0-\\u17e9\\u17f0-\\u17f9\\u1810-\\u1819\\u1820-\\u1878\\u1880-\\u1884\\u1887-\\u18a8\\u18aa\\u18b0-\\u18f5\\u1900-\\u191e\\u1946-\\u196d\\u1970-\\u1974\\u1980-\\u19ab\\u19b0-\\u19c9\\u19d0-\\u19da\\u1a00-\\u1a16\\u1a20-\\u1a54\\u1a80-\\u1a89\\u1a90-\\u1a99\\u1aa7\\u1b05-\\u1b33\\u1b45-\\u1b4c\\u1b50-\\u1b59\\u1b83-\\u1ba0\\u1bae-\\u1be5\\u1c00-\\u1c23\\u1c40-\\u1c49\\u1c4d-\\u1c7d\\u1c80-\\u1c88\\u1c90-\\u1cba\\u1cbd-\\u1cbf\\u1ce9-\\u1cec\\u1cee-\\u1cf3\\u1cf5\\u1cf6\\u1cfa\\u1d00-\\u1dbf\\u1e00-\\u1f15\\u1f18-\\u1f1d\\u1f20-\\u1f45\\u1f48-\\u1f4d\\u1f50-\\u1f57\\u1f59\\u1f5b\\u1f5d\\u1f5f-\\u1f7d\\u1f80-\\u1fb4\\u1fb6-\\u1fbc\\u1fbe\\u1fc2-\\u1fc4\\u1fc6-\\u1fcc\\u1fd0-\\u1fd3\\u1fd6-\\u1fdb\\u1fe0-\\u1fec\\u1ff2-\\u1ff4\\u1ff6-\\u1ffc\\u2070\\u2071\\u2074-\\u2079\\u207f-\\u2089\\u2090-\\u209c\\u2102\\u2107\\u210a-\\u2113\\u2115\\u2119-\\u211d\\u2124\\u2126\\u2128\\u212a-\\u212d\\u212f-\\u2139\\u213c-\\u213f\\u2145-\\u2149\\u214e\\u2150-\\u2189\\u2460-\\u249b\\u24ea-\\u24ff\\u2776-\\u2793\\u2c00-\\u2ce4\\u2ceb-\\u2cee\\u2cf2\\u2cf3\\u2cfd\\u2d00-\\u2d25\\u2d27\\u2d2d\\u2d30-\\u2d67\\u2d6f\\u2d80-\\u2d96\\u2da0-\\u2da6\\u2da8-\\u2dae\\u2db0-\\u2db6\\u2db8-\\u2dbe\\u2dc0-\\u2dc6\\u2dc8-\\u2dce\\u2dd0-\\u2dd6\\u2dd8-\\u2dde\\u2e2f\\u3005-\\u3007\\u3021-\\u3029\\u3031-\\u3035\\u3038-\\u303c\\u3041-\\u3096\\u309d-\\u309f\\u30a1-\\u30fa\\u30fc-\\u30ff\\u3105-\\u312f\\u3131-\\u318e\\u3192-\\u3195\\u31a0-\\u31bf\\u31f0-\\u31ff\\u3220-\\u3229\\u3248-\\u324f\\u3251-\\u325f\\u3280-\\u3289\\u32b1-\\u32bf\\u3400-\\u4dbf\\u4e00-\\ua48c\\ua4d0-\\ua4fd\\ua500-\\ua60c\\ua610-\\ua62b\\ua640-\\ua66e\\ua67f-\\ua69d\\ua6a0-\\ua6ef\\ua717-\\ua71f\\ua722-\\ua788\\ua78b-\\ua7ca\\ua7d0\\ua7d1\\ua7d3\\ua7d5-\\ua7d9\\ua7f2-\\ua801\\ua803-\\ua805\\ua807-\\ua80a\\ua80c-\\ua822\\ua830-\\ua835\\ua840-\\ua873\\ua882-\\ua8b3\\ua8d0-\\ua8d9\\ua8f2-\\ua8f7\\ua8fb\\ua8fd\\ua8fe\\ua900-\\ua925\\ua930-\\ua946\\ua960-\\ua97c\\ua984-\\ua9b2\\ua9cf-\\ua9d9\\ua9e0-\\ua9e4\\ua9e6-\\ua9fe\\uaa00-\\uaa28\\uaa40-\\uaa42\\uaa44-\\uaa4b\\uaa50-\\uaa59\\uaa60-\\uaa76\\uaa7a\\uaa7e-\\uaaaf\\uaab1\\uaab5\\uaab6\\uaab9-\\uaabd\\uaac0\\uaac2\\uaadb-\\uaadd\\uaae0-\\uaaea\\uaaf2-\\uaaf4\\uab01-\\uab06\\uab09-\\uab0e\\uab11-\\uab16\\uab20-\\uab26\\uab28-\\uab2e\\uab30-\\uab5a\\uab5c-\\uab69\\uab70-\\uabe2\\uabf0-\\uabf9\\uac00-\\ud7a3\\ud7b0-\\ud7c6\\ud7cb-\\ud7fb\\uf900-\\ufa6d\\ufa70-\\ufad9\\ufb00-\\ufb06\\ufb13-\\ufb17\\ufb1d\\ufb1f-\\ufb28\\ufb2a-\\ufb36\\ufb38-\\ufb3c\\ufb3e\\ufb40\\ufb41\\ufb43\\ufb44\\ufb46-\\ufbb1\\ufbd3-\\ufd3d\\ufd50-\\ufd8f\\ufd92-\\ufdc7\\ufdf0-\\ufdfb\\ufe70-\\ufe74\\ufe76-\\ufefc\\uff10-\\uff19\\uff21-\\uff3a\\uff41-\\uff5a\\uff66-\\uffbe\\uffc2-\\uffc7\\uffca-\\uffcf\\uffd2-\\uffd7\\uffda-\\uffdc";

const WORD_BOUNDARY = `(?:(?<![${SOURCE_WORD}])(?=[${SOURCE_WORD}])|(?<=[${SOURCE_WORD}])(?![${SOURCE_WORD}]))`;
const WORD_NONBOUNDARY = `(?:(?<=[${SOURCE_WORD}])(?=[${SOURCE_WORD}])|(?<![${SOURCE_WORD}])(?![${SOURCE_WORD}]))`;

/**
 * Expand \s \S \w \W \b \B to explicit source-semantics constructs,
 * walking the pattern so escapes and character-class state are
 * respected. Inside a class: \s and \w become bare fragments, \b stays
 * (it is a backspace there), \S and \W throw — their complements cannot
 * be expressed as class fragments. Outside: \b/\B become the lookaround
 * pair over the source word class. Must stay behavior-identical with
 * the Python loader's expansion.
 */
export function expandPortableEscapes(source: string): string {
  let out = "";
  let inClass = false;
  for (let i = 0; i < source.length; i += 1) {
    const ch = source[i];
    if (ch === "\\" && i + 1 < source.length) {
      const next = source[i + 1];
      if (next === "s") {
        out += inClass ? SOURCE_WHITESPACE : `[${SOURCE_WHITESPACE}]`;
        i += 1;
        continue;
      }
      if (next === "w") {
        out += inClass ? SOURCE_WORD : `[${SOURCE_WORD}]`;
        i += 1;
        continue;
      }
      if (next === "S" || next === "W") {
        if (inClass) {
          throw new Error(
            `\\${next} inside a character class cannot be expanded portably`,
          );
        }
        out += `[^${next === "S" ? SOURCE_WHITESPACE : SOURCE_WORD}]`;
        i += 1;
        continue;
      }
      if (next === "b" && !inClass) {
        out += WORD_BOUNDARY;
        i += 1;
        continue;
      }
      if (next === "B") {
        if (inClass) {
          throw new Error(
            "\\B inside a character class cannot be expanded portably",
          );
        }
        out += WORD_NONBOUNDARY;
        i += 1;
        continue;
      }
      out += ch + next;
      i += 1;
      continue;
    }
    if (ch === "[" && !inClass) inClass = true;
    else if (ch === "]" && inClass) inClass = false;
    out += ch;
  }
  return out;
}

/**
 * Reject constructs whose behavior differs between Python re (with
 * re.ASCII) and JS RegExp (without u). Returns violation strings; empty
 * means the pattern is inside the shared dialect. Lookbehind passes here
 * deliberately: Python re only compiles fixed-width lookbehind, where JS
 * semantics coincide, and the dual-runtime vector check rejects any
 * table Python cannot compile. \uXXXX escapes pass because both engines
 * read them identically in patterns (measured, not assumed); only the
 * braced JS-only \u{…} form is banned.
 */
export function validateGrammarPattern(source: string): string[] {
  const violations: string[] = [];
  if (/\(\?P/.test(source)) {
    violations.push("(?P named-group syntax: author JS-style (?<name>…)");
  }
  if (/\\[pP]\{/.test(source)) {
    violations.push("\\p{…} classes: Python re has no support");
  }
  for (const match of source.matchAll(/\(\?([a-zA-Z-]+)[:)]/g)) {
    violations.push(`inline flags (?${match[1]}…: banned; use table flags`);
  }
  if (/(?:^|[^\\])\(\?\(/.test(source)) {
    // An escaped \(? followed by a group reads as "(?(" to a substring
    // scan; require the opening paren to be unescaped. A conditional that
    // slips past this still fails JS compilation in the vector run.
    violations.push("conditional groups: not portable");
  }
  if (/\\u\{/.test(source)) {
    violations.push(
      "braced \\u{…} escape: JS-only (needs the u flag); use \\uXXXX or the literal character",
    );
  }
  return violations;
}

export function validateGrammarEntry(
  entry: GrammarEntry,
  defs: Record<string, string> = {},
): string[] {
  let expanded: string;
  try {
    expanded = expandGrammarPattern(entry.pattern, defs);
  } catch (error) {
    return [`${entry.id}: ${error instanceof Error ? error.message : String(error)}`];
  }
  const violations = validateGrammarPattern(expanded).map(
    (violation) => `${entry.id}: ${violation}`,
  );
  if (!/^[ims]*$/.test(entry.flags)) {
    violations.push(`${entry.id}: flags must be a subset of "ims"`);
  }
  return violations;
}

/** Compile for JS: defs and portable escapes expanded, global, never u. */
export function compileGrammarEntry(
  entry: GrammarEntry,
  defs: Record<string, string> = {},
): RegExp {
  return new RegExp(
    expandPortableEscapes(expandGrammarPattern(entry.pattern, defs)),
    `${entry.flags}g`,
  );
}

export function canonicalizeGroups(
  groups: Record<string, string>,
  rules: GrammarCanonical,
): Record<string, string> {
  const out: Record<string, string> = { ...groups };
  for (const name of rules.lowercase ?? []) {
    if (out[name] !== undefined) out[name] = out[name].toLowerCase();
  }
  for (const [name, chars] of Object.entries(rules.strip ?? {})) {
    if (out[name] !== undefined) {
      out[name] = out[name]
        .split("")
        .filter((ch) => !chars.includes(ch))
        .join("");
    }
  }
  for (const [name, mapping] of Object.entries(rules.map ?? {})) {
    if (out[name] !== undefined && mapping[out[name]] !== undefined) {
      out[name] = mapping[out[name]];
    }
  }
  return out;
}

export interface VectorFailure {
  id: string;
  input: string;
  reason: string;
}

/** Run every vector of every entry; empty result = the table holds. */
export function runGrammarVectors(table: GrammarTable): VectorFailure[] {
  const failures: VectorFailure[] = [];
  for (const entry of table.entries) {
    for (const violation of validateGrammarEntry(entry, table.defs)) {
      failures.push({ id: entry.id, input: "", reason: violation });
    }
    let re: RegExp;
    try {
      re = compileGrammarEntry(entry, table.defs);
    } catch (error) {
      failures.push({
        id: entry.id,
        input: "",
        reason: `does not compile in JS: ${String(error)}`,
      });
      continue;
    }
    for (const vector of entry.vectors) {
      re.lastIndex = 0;
      const match = re.exec(vector.input);
      if (vector.groups === null) {
        if (match) {
          failures.push({
            id: entry.id,
            input: vector.input,
            reason: `expected no match, got "${match[0]}"`,
          });
        }
        continue;
      }
      if (!match) {
        failures.push({
          id: entry.id,
          input: vector.input,
          reason: "expected a match, got none",
        });
        continue;
      }
      const got = { ...(match.groups ?? {}) };
      for (const [name, expected] of Object.entries(vector.groups)) {
        if (got[name] !== expected) {
          failures.push({
            id: entry.id,
            input: vector.input,
            reason: `group ${name}: expected "${expected}", got "${got[name]}"`,
          });
        }
      }
      if (vector.canonical) {
        const canon = canonicalizeGroups(
          got as Record<string, string>,
          entry.canonical,
        );
        for (const [name, expected] of Object.entries(vector.canonical)) {
          if (canon[name] !== expected) {
            failures.push({
              id: entry.id,
              input: vector.input,
              reason: `canonical ${name}: expected "${expected}", got "${canon[name]}"`,
            });
          }
        }
      }
    }
  }
  return failures;
}
